//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroCms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicroCms.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Web;
        ///
        ///namespace MicroCms.Resources
        ///{
        ///    public class SimpleClass
        ///    {
        ///        public SimpleClass()
        ///        {
        ///            _Value = new Lazy&lt;int&gt;(() =&gt; new Random(DateTime.Now.Millisecond).Next());
        ///        }
        ///
        ///        private Lazy&lt;int&gt; _Value;
        ///
        ///        public int Value { get { return _Value.Value; } }
        ///        public string Name { get; private set; }
        ///    }
        ///}.
        /// </summary>
        internal static string SimpleClass {
            get {
                return ResourceManager.GetString("SimpleClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Hello, Markdown
        ///
        ///Look at how classy we are:
        ///
        ///    public class Thing 
        ///	{
        ///		public string Name { get; set; }
        ///
        ///		public int GetLength()
        ///		{
        ///			return -1;
        ///		}
        ///	}
        ///
        ///And now we&apos;re done..
        /// </summary>
        internal static string SimpleExample {
            get {
                return ResourceManager.GetString("SimpleExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///function DoSomething(name) {
        ///    console.log(&apos;doing something with: &apos; + name);
        ///}.
        /// </summary>
        internal static string SimpleScript {
            get {
                return ResourceManager.GetString("SimpleScript", resourceCulture);
            }
        }
    }
}
